malloc:malloc.c Makefile
	gcc -g -Wall -o malloc malloc.c

type_traits: type_traits.cpp Makefile
	g++ -g -Wall -o type_traits type_traits.cpp

vector: vector.cpp Makefile
	g++ -g -Wall -o vector vector.cpp

deuqe: deuqe.cpp Makefile
	g++ -g -Wall -o deuqe deuqe.cpp

hashtable: hashtable.cpp Makefile
	g++ -g -Wall -o hashtable hashtable.cpp

sort: sort_compare.cpp Makefile
	g++ -g -Wall -o sort sort_compare.cpp

clean:
	rm -rf malloc
	rm -rf type_traits
	rm -rf vector
	rm -rf hashtable
	rm -rf sort
	rm -rf deuqe